language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-sklearn.txt
  - pip install -r requirements-nextcloudtag.txt

before_script:
  - echo "USE mysql;\nSET PASSWORD FOR root@'localhost' = PASSWORD('root');;\nFLUSH PRIVILEGES;\n" | mysql -u root

script:
  - python manage.py test

services:
  - mysql

notifications:
  email: 
    - sebastien.renard@digitalfox.org
